language: node_js
node_js:
- '8'
before_deploy:
- npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep-history: true
    local-dir: .site
    on:
      branch: master